/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SpherePreviewRouteImport } from './routes/sphere-preview'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IHashRouteImport } from './routes/i.$hash'
import { Route as AppWelcomeRouteImport } from './routes/_app.welcome'
import { Route as AppUpgradeRouteImport } from './routes/_app.upgrade'
import { Route as AppTestShareRouteImport } from './routes/_app.test-share'
import { Route as AppSitemapRouteImport } from './routes/_app.sitemap'
import { Route as AppSentRouteImport } from './routes/_app.sent'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPhoneRouteImport } from './routes/_app.phone'
import { Route as AppOnboardingImportRouteImport } from './routes/_app.onboarding-import'
import { Route as AppOnboardingExplainerRouteImport } from './routes/_app.onboarding-explainer'
import { Route as AppMatchesRouteImport } from './routes/_app.matches'
import { Route as AppMatchRouteImport } from './routes/_app.match'
import { Route as AppInstagramRouteImport } from './routes/_app.instagram'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppContactsRouteImport } from './routes/_app.contacts'
import { Route as AppCodeRouteImport } from './routes/_app.code'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppAddRouteImport } from './routes/_app.add'
import { Route as AppAddIndexRouteImport } from './routes/_app.add.index'
import { Route as AppThreadHashRouteImport } from './routes/_app.thread.$hash'
import { Route as AppProfileInviteRouteImport } from './routes/_app.profile.invite'
import { Route as AppProfileDeleteRouteImport } from './routes/_app.profile.delete'
import { Route as AppAddPatienceRouteImport } from './routes/_app.add.patience'
import { Route as AppAddManualRouteImport } from './routes/_app.add.manual'
import { Route as AppAddContactsRouteImport } from './routes/_app.add.contacts'
import { Route as AppAddConfirmRouteImport } from './routes/_app.add.confirm'
import { Route as AppAddComposeRouteImport } from './routes/_app.add.compose'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SpherePreviewRoute = SpherePreviewRouteImport.update({
  id: '/sphere-preview',
  path: '/sphere-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IHashRoute = IHashRouteImport.update({
  id: '/i/$hash',
  path: '/i/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWelcomeRoute = AppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppRoute,
} as any)
const AppUpgradeRoute = AppUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AppRoute,
} as any)
const AppTestShareRoute = AppTestShareRouteImport.update({
  id: '/test-share',
  path: '/test-share',
  getParentRoute: () => AppRoute,
} as any)
const AppSitemapRoute = AppSitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => AppRoute,
} as any)
const AppSentRoute = AppSentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPhoneRoute = AppPhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingImportRoute = AppOnboardingImportRouteImport.update({
  id: '/onboarding-import',
  path: '/onboarding-import',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingExplainerRoute = AppOnboardingExplainerRouteImport.update({
  id: '/onboarding-explainer',
  path: '/onboarding-explainer',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchesRoute = AppMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchRoute = AppMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AppRoute,
} as any)
const AppInstagramRoute = AppInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppCodeRoute = AppCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAddRoute = AppAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppRoute,
} as any)
const AppAddIndexRoute = AppAddIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAddRoute,
} as any)
const AppThreadHashRoute = AppThreadHashRouteImport.update({
  id: '/thread/$hash',
  path: '/thread/$hash',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileInviteRoute = AppProfileInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppProfileDeleteRoute = AppProfileDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppAddPatienceRoute = AppAddPatienceRouteImport.update({
  id: '/patience',
  path: '/patience',
  getParentRoute: () => AppAddRoute,
} as any)
const AppAddManualRoute = AppAddManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => AppAddRoute,
} as any)
const AppAddContactsRoute = AppAddContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppAddRoute,
} as any)
const AppAddConfirmRoute = AppAddConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => AppAddRoute,
} as any)
const AppAddComposeRoute = AppAddComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AppAddRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/sphere-preview': typeof SpherePreviewRoute
  '/terms': typeof TermsRoute
  '/add': typeof AppAddRouteWithChildren
  '/admin': typeof AppAdminRoute
  '/code': typeof AppCodeRoute
  '/contacts': typeof AppContactsRoute
  '/home': typeof AppHomeRoute
  '/instagram': typeof AppInstagramRoute
  '/match': typeof AppMatchRoute
  '/matches': typeof AppMatchesRoute
  '/onboarding-explainer': typeof AppOnboardingExplainerRoute
  '/onboarding-import': typeof AppOnboardingImportRoute
  '/phone': typeof AppPhoneRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/sent': typeof AppSentRoute
  '/sitemap': typeof AppSitemapRoute
  '/test-share': typeof AppTestShareRoute
  '/upgrade': typeof AppUpgradeRoute
  '/welcome': typeof AppWelcomeRoute
  '/i/$hash': typeof IHashRoute
  '/add/compose': typeof AppAddComposeRoute
  '/add/confirm': typeof AppAddConfirmRoute
  '/add/contacts': typeof AppAddContactsRoute
  '/add/manual': typeof AppAddManualRoute
  '/add/patience': typeof AppAddPatienceRoute
  '/profile/delete': typeof AppProfileDeleteRoute
  '/profile/invite': typeof AppProfileInviteRoute
  '/thread/$hash': typeof AppThreadHashRoute
  '/add/': typeof AppAddIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/sphere-preview': typeof SpherePreviewRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AppAdminRoute
  '/code': typeof AppCodeRoute
  '/contacts': typeof AppContactsRoute
  '/home': typeof AppHomeRoute
  '/instagram': typeof AppInstagramRoute
  '/match': typeof AppMatchRoute
  '/matches': typeof AppMatchesRoute
  '/onboarding-explainer': typeof AppOnboardingExplainerRoute
  '/onboarding-import': typeof AppOnboardingImportRoute
  '/phone': typeof AppPhoneRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/sent': typeof AppSentRoute
  '/sitemap': typeof AppSitemapRoute
  '/test-share': typeof AppTestShareRoute
  '/upgrade': typeof AppUpgradeRoute
  '/welcome': typeof AppWelcomeRoute
  '/i/$hash': typeof IHashRoute
  '/add/compose': typeof AppAddComposeRoute
  '/add/confirm': typeof AppAddConfirmRoute
  '/add/contacts': typeof AppAddContactsRoute
  '/add/manual': typeof AppAddManualRoute
  '/add/patience': typeof AppAddPatienceRoute
  '/profile/delete': typeof AppProfileDeleteRoute
  '/profile/invite': typeof AppProfileInviteRoute
  '/thread/$hash': typeof AppThreadHashRoute
  '/add': typeof AppAddIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sphere-preview': typeof SpherePreviewRoute
  '/terms': typeof TermsRoute
  '/_app/add': typeof AppAddRouteWithChildren
  '/_app/admin': typeof AppAdminRoute
  '/_app/code': typeof AppCodeRoute
  '/_app/contacts': typeof AppContactsRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/instagram': typeof AppInstagramRoute
  '/_app/match': typeof AppMatchRoute
  '/_app/matches': typeof AppMatchesRoute
  '/_app/onboarding-explainer': typeof AppOnboardingExplainerRoute
  '/_app/onboarding-import': typeof AppOnboardingImportRoute
  '/_app/phone': typeof AppPhoneRoute
  '/_app/profile': typeof AppProfileRouteWithChildren
  '/_app/sent': typeof AppSentRoute
  '/_app/sitemap': typeof AppSitemapRoute
  '/_app/test-share': typeof AppTestShareRoute
  '/_app/upgrade': typeof AppUpgradeRoute
  '/_app/welcome': typeof AppWelcomeRoute
  '/i/$hash': typeof IHashRoute
  '/_app/add/compose': typeof AppAddComposeRoute
  '/_app/add/confirm': typeof AppAddConfirmRoute
  '/_app/add/contacts': typeof AppAddContactsRoute
  '/_app/add/manual': typeof AppAddManualRoute
  '/_app/add/patience': typeof AppAddPatienceRoute
  '/_app/profile/delete': typeof AppProfileDeleteRoute
  '/_app/profile/invite': typeof AppProfileInviteRoute
  '/_app/thread/$hash': typeof AppThreadHashRoute
  '/_app/add/': typeof AppAddIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/sphere-preview'
    | '/terms'
    | '/add'
    | '/admin'
    | '/code'
    | '/contacts'
    | '/home'
    | '/instagram'
    | '/match'
    | '/matches'
    | '/onboarding-explainer'
    | '/onboarding-import'
    | '/phone'
    | '/profile'
    | '/sent'
    | '/sitemap'
    | '/test-share'
    | '/upgrade'
    | '/welcome'
    | '/i/$hash'
    | '/add/compose'
    | '/add/confirm'
    | '/add/contacts'
    | '/add/manual'
    | '/add/patience'
    | '/profile/delete'
    | '/profile/invite'
    | '/thread/$hash'
    | '/add/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/sphere-preview'
    | '/terms'
    | '/admin'
    | '/code'
    | '/contacts'
    | '/home'
    | '/instagram'
    | '/match'
    | '/matches'
    | '/onboarding-explainer'
    | '/onboarding-import'
    | '/phone'
    | '/profile'
    | '/sent'
    | '/sitemap'
    | '/test-share'
    | '/upgrade'
    | '/welcome'
    | '/i/$hash'
    | '/add/compose'
    | '/add/confirm'
    | '/add/contacts'
    | '/add/manual'
    | '/add/patience'
    | '/profile/delete'
    | '/profile/invite'
    | '/thread/$hash'
    | '/add'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/privacy'
    | '/sphere-preview'
    | '/terms'
    | '/_app/add'
    | '/_app/admin'
    | '/_app/code'
    | '/_app/contacts'
    | '/_app/home'
    | '/_app/instagram'
    | '/_app/match'
    | '/_app/matches'
    | '/_app/onboarding-explainer'
    | '/_app/onboarding-import'
    | '/_app/phone'
    | '/_app/profile'
    | '/_app/sent'
    | '/_app/sitemap'
    | '/_app/test-share'
    | '/_app/upgrade'
    | '/_app/welcome'
    | '/i/$hash'
    | '/_app/add/compose'
    | '/_app/add/confirm'
    | '/_app/add/contacts'
    | '/_app/add/manual'
    | '/_app/add/patience'
    | '/_app/profile/delete'
    | '/_app/profile/invite'
    | '/_app/thread/$hash'
    | '/_app/add/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SpherePreviewRoute: typeof SpherePreviewRoute
  TermsRoute: typeof TermsRoute
  IHashRoute: typeof IHashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sphere-preview': {
      id: '/sphere-preview'
      path: '/sphere-preview'
      fullPath: '/sphere-preview'
      preLoaderRoute: typeof SpherePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$hash': {
      id: '/i/$hash'
      path: '/i/$hash'
      fullPath: '/i/$hash'
      preLoaderRoute: typeof IHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/welcome': {
      id: '/_app/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AppWelcomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/upgrade': {
      id: '/_app/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AppUpgradeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/test-share': {
      id: '/_app/test-share'
      path: '/test-share'
      fullPath: '/test-share'
      preLoaderRoute: typeof AppTestShareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sitemap': {
      id: '/_app/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof AppSitemapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sent': {
      id: '/_app/sent'
      path: '/sent'
      fullPath: '/sent'
      preLoaderRoute: typeof AppSentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/phone': {
      id: '/_app/phone'
      path: '/phone'
      fullPath: '/phone'
      preLoaderRoute: typeof AppPhoneRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding-import': {
      id: '/_app/onboarding-import'
      path: '/onboarding-import'
      fullPath: '/onboarding-import'
      preLoaderRoute: typeof AppOnboardingImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding-explainer': {
      id: '/_app/onboarding-explainer'
      path: '/onboarding-explainer'
      fullPath: '/onboarding-explainer'
      preLoaderRoute: typeof AppOnboardingExplainerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/matches': {
      id: '/_app/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AppMatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/match': {
      id: '/_app/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof AppMatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/instagram': {
      id: '/_app/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof AppInstagramRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/code': {
      id: '/_app/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof AppCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/add': {
      id: '/_app/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AppAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/add/': {
      id: '/_app/add/'
      path: '/'
      fullPath: '/add/'
      preLoaderRoute: typeof AppAddIndexRouteImport
      parentRoute: typeof AppAddRoute
    }
    '/_app/thread/$hash': {
      id: '/_app/thread/$hash'
      path: '/thread/$hash'
      fullPath: '/thread/$hash'
      preLoaderRoute: typeof AppThreadHashRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/invite': {
      id: '/_app/profile/invite'
      path: '/invite'
      fullPath: '/profile/invite'
      preLoaderRoute: typeof AppProfileInviteRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/profile/delete': {
      id: '/_app/profile/delete'
      path: '/delete'
      fullPath: '/profile/delete'
      preLoaderRoute: typeof AppProfileDeleteRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/add/patience': {
      id: '/_app/add/patience'
      path: '/patience'
      fullPath: '/add/patience'
      preLoaderRoute: typeof AppAddPatienceRouteImport
      parentRoute: typeof AppAddRoute
    }
    '/_app/add/manual': {
      id: '/_app/add/manual'
      path: '/manual'
      fullPath: '/add/manual'
      preLoaderRoute: typeof AppAddManualRouteImport
      parentRoute: typeof AppAddRoute
    }
    '/_app/add/contacts': {
      id: '/_app/add/contacts'
      path: '/contacts'
      fullPath: '/add/contacts'
      preLoaderRoute: typeof AppAddContactsRouteImport
      parentRoute: typeof AppAddRoute
    }
    '/_app/add/confirm': {
      id: '/_app/add/confirm'
      path: '/confirm'
      fullPath: '/add/confirm'
      preLoaderRoute: typeof AppAddConfirmRouteImport
      parentRoute: typeof AppAddRoute
    }
    '/_app/add/compose': {
      id: '/_app/add/compose'
      path: '/compose'
      fullPath: '/add/compose'
      preLoaderRoute: typeof AppAddComposeRouteImport
      parentRoute: typeof AppAddRoute
    }
  }
}

interface AppAddRouteChildren {
  AppAddComposeRoute: typeof AppAddComposeRoute
  AppAddConfirmRoute: typeof AppAddConfirmRoute
  AppAddContactsRoute: typeof AppAddContactsRoute
  AppAddManualRoute: typeof AppAddManualRoute
  AppAddPatienceRoute: typeof AppAddPatienceRoute
  AppAddIndexRoute: typeof AppAddIndexRoute
}

const AppAddRouteChildren: AppAddRouteChildren = {
  AppAddComposeRoute: AppAddComposeRoute,
  AppAddConfirmRoute: AppAddConfirmRoute,
  AppAddContactsRoute: AppAddContactsRoute,
  AppAddManualRoute: AppAddManualRoute,
  AppAddPatienceRoute: AppAddPatienceRoute,
  AppAddIndexRoute: AppAddIndexRoute,
}

const AppAddRouteWithChildren =
  AppAddRoute._addFileChildren(AppAddRouteChildren)

interface AppProfileRouteChildren {
  AppProfileDeleteRoute: typeof AppProfileDeleteRoute
  AppProfileInviteRoute: typeof AppProfileInviteRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileDeleteRoute: AppProfileDeleteRoute,
  AppProfileInviteRoute: AppProfileInviteRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppRouteChildren {
  AppAddRoute: typeof AppAddRouteWithChildren
  AppAdminRoute: typeof AppAdminRoute
  AppCodeRoute: typeof AppCodeRoute
  AppContactsRoute: typeof AppContactsRoute
  AppHomeRoute: typeof AppHomeRoute
  AppInstagramRoute: typeof AppInstagramRoute
  AppMatchRoute: typeof AppMatchRoute
  AppMatchesRoute: typeof AppMatchesRoute
  AppOnboardingExplainerRoute: typeof AppOnboardingExplainerRoute
  AppOnboardingImportRoute: typeof AppOnboardingImportRoute
  AppPhoneRoute: typeof AppPhoneRoute
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppSentRoute: typeof AppSentRoute
  AppSitemapRoute: typeof AppSitemapRoute
  AppTestShareRoute: typeof AppTestShareRoute
  AppUpgradeRoute: typeof AppUpgradeRoute
  AppWelcomeRoute: typeof AppWelcomeRoute
  AppThreadHashRoute: typeof AppThreadHashRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAddRoute: AppAddRouteWithChildren,
  AppAdminRoute: AppAdminRoute,
  AppCodeRoute: AppCodeRoute,
  AppContactsRoute: AppContactsRoute,
  AppHomeRoute: AppHomeRoute,
  AppInstagramRoute: AppInstagramRoute,
  AppMatchRoute: AppMatchRoute,
  AppMatchesRoute: AppMatchesRoute,
  AppOnboardingExplainerRoute: AppOnboardingExplainerRoute,
  AppOnboardingImportRoute: AppOnboardingImportRoute,
  AppPhoneRoute: AppPhoneRoute,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppSentRoute: AppSentRoute,
  AppSitemapRoute: AppSitemapRoute,
  AppTestShareRoute: AppTestShareRoute,
  AppUpgradeRoute: AppUpgradeRoute,
  AppWelcomeRoute: AppWelcomeRoute,
  AppThreadHashRoute: AppThreadHashRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SpherePreviewRoute: SpherePreviewRoute,
  TermsRoute: TermsRoute,
  IHashRoute: IHashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
